baseURL = 'https://timestamps.oyasumi99.com/'
languageCode = 'en-us'
title = 'Kamo Timestamps'
theme = 'terminal'
baseurl = "/"
pagination.pagerSize = 5

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  enableGitInfo = true

  favicon = "favicon.png"

   [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "main"
      name = "Main"
      url = "/posts/main"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "links"
      name = "Links"
      url = "/links"
      weight = 2

  [languages.en.params.logo]
    logoText = "Kamo Timestamps"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
